// LOGIN FORM
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_CHANGE = 'LOGIN_CHANGE';
// GOOGLE AUTH
export const GOAUTH_REQUEST = 'GOAUTH_REQUEST';
export const GOAUTH_SUCCESS = 'GOAUTH_SUCCESS';
export const GOAUTH_FAILURE = 'GOAUTH_FAILURE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
